# generated by datamodel-codegen:
#   filename:  openapi_frontend.yaml
#   timestamp: 2023-02-14T15:30:30+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Tenant(BaseModel):
    id: int | None = Field(
        None,
        description='Unique ID of the Tenant generated by the service. User API can not pass this for create operation',
        example=1,
    )
    name: str = Field(..., description='Unique name of the tenant', example='Tenant A')
    description: str | None = Field(
        None, description='Description about tenant', example='Tenant A for ACME LLC.'
    )
    vlan_range: str | None = Field(
        None,
        alias='vlan-range',
        description='Range of VLANs to reserve for the tenant',
        example='10-20,50-60',
    )


class Operation(Enum):
    vlan_add = 'vlan-add'
    vlan_delete = 'vlan-delete'
    vlan_update = 'vlan-update'


class TenantUpdate(BaseModel):
    operation: Operation = Field(
        ...,
        description='Add, delete or update tenant configuration',
        example='vlan-update',
    )
    tenant: Tenant | None = None


class TenantList(BaseModel):
    tenant: list[Tenant] | None = None
